### ISSUE TITLE
Count Error in Recent PHP versions

### ISSUE THREAD

**Issue by AWOL-TECH** [MIGHTYminnow/equal-height-columns#4]
I experience this issue with php 7.4 but think it exists since 7.2.

It's not a breaking error but it absolutely spams the error log 

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in ../wp-content/plugins/equal-height-columns/admin/class-equal-height-columns-admin.php on line 248

The issue has been referenced on the WP Plugin page

https://wordpress.org/support/topic/php-7-2-count/

https://wordpress.org/support/topic/warning-in-line-248-and-solution/

Could you please publish a further update to include a fix

Thank you

**Comment by aebs90** [comment]
This issue was resolved on Apr 27, 2021 https://github.com/MIGHTYminnow/equal-height-columns/commit/041e8c0117989fbc4a5a7cbfc7aadee87b2668da

@AWOL-TECH Sorry we didn't reply to this, we missed this issue report before.
